version: '3.8'

services:
  # Backend Service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - CRAWL4AI_API_URL=http://crawl4ai:8888
      - VECTOR_DB_URL=http://vectordb:6333
    depends_on:
      - searxng
      - crawl4ai
      - vectordb

  # # Frontend Service
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend

  # SearXNG Service
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    environment:
      - INSTANCE_NAME=SearXNG VN
      - BASE_URL=http://localhost:8080/
      - ENABLE_METRICS=0
      - FILTRON=0
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=8
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
      - ./searxng/data:/usr/local/searxng/data
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Crawl4AI Service
  crawl4ai:
    image: unclecode/crawl4ai:latest
    ports:
      - "8888:8888"
    volumes:
      - ./crawl4ai/config:/app/config
      - ./crawl4ai/data:/app/data
    environment:
      - CRAWL4AI_LOG_LEVEL=INFO
    restart: unless-stopped

  # Vector Database
  vectordb:
    image: qdrant/qdrant:v1.7.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3