server:
  secret_key: "abcdefghijklmnopqrstuvwxyz0123456789"
  base_url: http://localhost:8080/
  limiter: false
  image_proxy: true
  method: GET
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

search:
  safe_search: 0
  autocomplete: 'google'
  language: 'vi'
  query_in_title: true
  formats:
    - html
    - json
  default_format: html

ui:
  default_theme: simple
  theme_args:
    simple_style: auto
  static_use_hash: true
  query_in_title: true
  center_alignment: true
  results_on_new_tab: false
  infinite_scroll: true

engines:
  - name: google
    engine: google
    shortcut: go
    use_mobile_ui: false
    disabled: false
    custom:
      country: VN
  
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false
    custom:
      country: VN
      language: vi-VN
  
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
    custom:
      region: vn-vi
  
  - name: brave
    engine: brave
    shortcut: br
    disabled: false
  
  - name: yahoo
    engine: yahoo
    shortcut: yh
    disabled: false

outgoing:
  request_timeout: 10.0
  useragent_suffix: "SearXNG_VN"
  pool_connections: 100
  pool_maxsize: 100
  retries: 2
  
general:
  debug: false
  instance_name: "PhonePriceComparisonSearch"
  contact_url: false
  enable_metrics: true

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'

default_doi_resolver: 'oadoi.org'

locales:
  en: English
  vi: Tiếng Việt